# Research


## Working Papers

**The Effects of Business Leaders' Written Language on Public Reactions in Live Online Forums** <br>
with Valentyna Melnyk, Valeria Noguti, and Harald J. van Heerde

[**Separating the Artist from the Art: Social Media Boycotts, Platform Sanctions, and Music Consumption**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4929261) <br>
with Nils Wlömert and Jūra Liaukonytė

[**The Impact of Social Media on Music Demand: Evidence from a Quasi-Natural Experiment**](https://arxiv.org/abs/2405.14999) <br>
with Christian Hotz-Behofsits, Nils Wlömert, Dominik Papies, and Jūra
Liaukonytė

[**Negative Spillover Effects of Opt-out Defaults: Evidence from Organ Donation Policies**](https://osf.io/preprints/psyarxiv/c36v8) <br> 
with Pascal Güntürkün, Sinika Studte, Michel Clement, Eva-Maria Merz,
Jonathan Tan,<br>
Elisabeth Huis in 't Veld, and Eamonn Ferguson

[**A Bayesian Survival Model for Time Varying Coefficients and Unobserved Heterogeneity**](https://arxiv.org/abs/2206.11320)\
with Peter Knaus

## Work in Progress

**The Personal Side of Human Brands: How Human Brand Messages on Social Media Drive Brand Consumption and Engagement**\
with Christian Hotz-Behofsits, Nils Wlömert, and Harald J. van Heerde

**The Hot 100 - The Influence of Weather patterns and Music
Consumption**\
with Vartan Bal and Valentyna Melnyk

**The Path to Fame - Exploiting Curator Networks to Predict Human Brand
Success**\
(presented at the Workshop for Information Systems and Economics,
Marketing Science Conference, EMAC Doctoral Colloquium, EMAC Annual
Conference, and Economics of the Music Industry)\
with Nils Wlömert, Lev Muchnik, and Jacob Goldenberg

[**Political Polarization Indices for Top Music Artists**](https://liaukonyte.dyson.cornell.edu/music/)\
with Jūra Liaukonytė and Nils Wlömert

[**B-DiD - A Dynamic Bayesian Approach to Difference-in-Differences**](https://dwinkler.org/bdids/#/title-slide)\
(presented at Marketing Science Conference)\
with Peter Knaus and Pascal Güntürkün

## Multidisciplinary

[**Negative Spillover Effects of Opt-out Defaults: Evidence from Organ Donation Policies**](https://doi.org/10.1093/pnasnexus/pgaf311) (PNAS Nexus) <br> 
with Pascal Güntürkün, Sinika Studte, Michel Clement, Eva-Maria Merz,
Jonathan Tan,<br>
Elisabeth Huis in 't Veld, and Eamonn Ferguson, 2025
[Featured in multiple news outlets](https://oxfordjournals.altmetric.com/details/182973845/news)

## Medicine 

[**Systemic Immune-Inflammation Index (SII) Predicts Poor Survival in Pancreatic Cancer Patients Undergoing Resection**](https://link.springer.com/article/10.1007/s11605-019-04187-z) (*Journal of
Gastrointestinal Surgery*)\
with Gerd Jomrich, Elisabeth S. Gruber, Marlene Hollenstein, Michael
Gnantand, Klaus Sahora, and Martin Schindl, 2020

[**Expression of FGF8, FGF18, and FGFR4 in Gastroesophageal Adenocarcinomas**](https://www.mdpi.com/2073-4409/8/9/1092) ([*Cells*]{.underline})\
with Gerd Jomrich, Xenia Hudec, Felix Harpain, Gerald Timelthaler,
Thomas Mohr, Brigitte Marian, and Sebastian F. Schoppmann, 2019

[**MK2 and ETV1 Are Prgonistic Factors in Esophageal Adenocarcinomas**](https://www.jcancer.org/v09p0460.htm)
([*Journal of Cancer*]{.underline})\
with Gerd Jomrich, Florian Maroske, Jasmin Stieger, Matthias Preusser,
Aysegül Ilhan-Mutlu, Ivan Kristo, Matthias Paireder, and Sebastian F.
Schoppmann, 2018
